### PR TITLE
Add unit tests for github com.github.jbduncan.gradle.refaster.Utils and com.github.jbduncan.collect.testing

### PR DESCRIPTION
**Pull request by paulkennethkent**
## Overview

Thank you for your submission to generate tests using Diffblue Cover. 

One of the new tools introduced into our product is a test ranking system which helps to filter the best tests generated by Diffblue Cover before submitting the PR. We then internally review the other tests to see where we can make improvements. it would be good to get your feedback on these tests. 

Hopefully, these tests will help you detect any regressions caused by future code changes.

If you find these tests useful then I'll be more then happy to refactor them to use Junit 5 which isn't currently supported.

### CODE REVIEW

**Comment by jbduncan** [comment]
Hi @paulkennethkent - sorry for the delay in responding! I was on holiday and then I was dealing with work and other IRL things. :bowing_man: 

Wow, thank you very much for the PR! Yes please, I'd love if it you could change the tests to use JUnit Jupiter.

I'd also love if you followed the [contribution guide](https://github.com/jbduncan/jupiter-collection-testers/blob/master/CONTRIBUTING.md) as best as you can.

(But feel free to ignore the advice to [add this PR's number to your commit(s)](https://github.com/jbduncan/jupiter-collection-testers/blob/master/CONTRIBUTING.md#commit-messages), because I intend to change that paragraph a bit in the future.)

If you otherwise have any questions, please ask and I'd be more than happy to help. :)

**Comment by jbduncan** [comment]
@paulkennethkent I just wanted to follow up on this. Do you have the time to change these tests into JUnit 5 ones, or would you prefer I do it myself? :)

**Comment by paulkennethkent** [comment]
Massive apologies for the delay @jbduncan I missed all of the notifications. 

I've made some changes, please let me know if you would like me to do anything else.

**Comment by jbduncan** [comment]
@paulkennethkent No worries! I wanted to apologise myself for taking so long to acknowledge your latest message.

Thank you for the brand new tests! To get things merged in, the CI build needs to be fixed first. To do so, please:

1. Run `./gradlew spotlessApply`.
2. Amend your last commit with the resulting code formatting changes.
3. Force push the new commit.

After that, I'll be more than happy to accept this PR. :)

**Comment by jbduncan** [comment]
Alternatively, you can enable [edit permissions](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for your branch, if they're not enabled already, and I'd be happy to clean up this PR for you.

**Comment by paulkennethkent** [comment]
@jbduncan done 👍

**Pull request closed without merging**
